const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

// Load .env file for local development (Vercel injects env vars automatically)
require('dotenv').config();

const supabaseUrl = process.env.SUPABASE_URL || '';
const supabaseKey = process.env.SUPABASE_PUBLISHABLE_KEY || '';
const adminEmail = process.env.ADMIN_EMAIL || '';
const adminEmails = process.env.ADMIN_EMAILS || adminEmail;

const config = `// Auto-generated by build.js — do not edit manually
window.NEPSOP_CONFIG = {
  SUPABASE_URL: ${JSON.stringify(supabaseUrl)},
  SUPABASE_PUBLISHABLE_KEY: ${JSON.stringify(supabaseKey)},
  ADMIN_EMAIL: ${JSON.stringify(adminEmail)},
  ADMIN_EMAILS: ${JSON.stringify(adminEmails)}
};
`;

const outputPath = path.join(__dirname, 'assets', 'js', 'config.js');
fs.mkdirSync(path.dirname(outputPath), { recursive: true });
fs.writeFileSync(outputPath, config, 'utf-8');
console.log('✅ config.js generated successfully');

// ---------------------------------------------------------------------------
// Static blog pages + sitemap.xml + llms.txt
// Runs after config generation. Requires SUPABASE_URL + SUPABASE_PUBLISHABLE_KEY
// to fetch blog content; otherwise it skips blog pages gracefully (local dev).
// ---------------------------------------------------------------------------
try {
  require('./generate-blog-pages.js');
} catch (err) {
  console.error('⚠️  Static blog generation failed:', err.message);
  process.exitCode = 1;
}
